{{- if (and .Values.namespace (eq (default false .Values.namespace.create) true)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Namespace }}
{{- end }}