{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "qb.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_SUPERUSER_PASSWORD: {{ required "secrets.postgres.superuserPassword is required" .Values.secrets.postgres.superuserPassword | quote }}
  POSTGRES_DB_PASSWORD: {{ required "secrets.postgres.appPassword is required" .Values.secrets.postgres.appPassword | quote }}
  KC_DB_PASSWORD: {{ required "secrets.postgres.keycloakPassword is required" .Values.secrets.postgres.keycloakPassword | quote }}

  KEYCLOAK_ADMIN_PASSWORD: {{ required "secrets.keycloak.adminPassword is required" .Values.secrets.keycloak.adminPassword | quote }}

  REDIS_PASS: {{ required "secrets.redis.password is required" .Values.secrets.redis.password | quote }}

  RABBITMQ_ADM_PASSWORD: {{ required "secrets.rabbitmq.adminPassword is required" .Values.secrets.rabbitmq.adminPassword | quote }}
  RABBITMQ_SENDER_PASSWORD: {{ required "secrets.rabbitmq.senderPassword is required" .Values.secrets.rabbitmq.senderPassword | quote }}
  RABBITMQ_RECIPIENT_PASSWORD: {{ required "secrets.rabbitmq.recipientPassword is required" .Values.secrets.rabbitmq.recipientPassword | quote }}

  MINIO_ROOT_PASSWORD: {{ required "secrets.minio.rootPassword is required" .Values.secrets.minio.rootPassword | quote }}

  FLASK_SECRET_KEY: {{ required "secrets.backend.flaskSecretKey is required" .Values.secrets.backend.flaskSecretKey | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ required "secrets.backend.keycloakClientSecret is required" .Values.secrets.backend.keycloakClientSecret | quote }}
{{- end }}
