{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: frontend
    {{- include "qb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: https
      port: {{ .Values.frontend.service.port }}
      targetPort: https
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    {{- include "qb.labels" . | nindent 4 }}
spec:
  replicas: {{ ternary .Values.frontend.autoscaling.minReplicas .Values.frontend.replicaCount .Values.frontend.autoscaling.enabled }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: frontend
        {{- include "qb.labels" . | nindent 8 }}
    spec:
      {{- include "qb.imagePullSecrets" . | nindent 6 }}
      initContainers:
        {{- include "qb.waitFor" (dict "name" "wait-backend" "host" .Values.backend.name "port" .Values.backend.service.port "timeout" 300) | nindent 8 }}
        {{- include "qb.waitFor" (dict "name" "wait-keycloak" "host" .Values.keycloak.name "port" .Values.keycloak.service.httpsPort "timeout" 300) | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "qb.image" (dict "image" .Values.frontend.image "global" .Values.global) }}
          imagePullPolicy: {{ include "qb.pullPolicy" (dict "image" .Values.frontend.image "global" .Values.global) }}
          ports:
            - name: https
              containerPort: 8443
          env:
            - name: FRONTEND_PORT
              value: {{ .Values.frontend.service.port | quote }}
            - name: BACKEND_HOST
              value: {{ .Values.backend.name | quote }}
            - name: BACKEND_PORT
              value: {{ .Values.backend.service.port | quote }}
            - name: KEYCLOAK_HOST
              value: {{ .Values.keycloak.name | quote }}
            - name: KEYCLOAK_PORT
              value: {{ .Values.keycloak.service.httpsPort | quote }}

          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: https
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: https
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
{{- end }}
