{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgres
    {{- include "qb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
{{- if eq .Values.postgres.service.type "NodePort" }}
      nodePort: {{ .Values.postgres.service.nodePort }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: postgres
    {{- include "qb.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.postgres.name }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: postgres
        {{- include "qb.labels" . | nindent 8 }}
    spec:
      {{- include "qb.imagePullSecrets" . | nindent 6 }}
      securityContext:
        fsGroup: 10000
      {{- if .Values.tls.enabled }}
      volumes:
        - name: qb-tls
          secret:
            secretName: {{ .Values.tls.name }}
            items:
              - key: certificate.crt
                path: certificate.crt
              - key: private.key
                path: private.key
              - key: sandbox_ca_root.crt
                path: sandbox_ca_root.crt
      {{- end }}
      containers:
        - name: postgres
          image: {{ include "qb.image" (dict "image" .Values.postgres.image "global" .Values.global) }}
          imagePullPolicy: {{ include "qb.pullPolicy" (dict "image" .Values.postgres.image "global" .Values.global) }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
          env:
            - name: PGDATA
              value: {{ .Values.postgres.env.pgdata | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.env.dbName | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.env.dbUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_DB_PASSWORD
            - name: POSTGRES_DB_HOST
              value: {{ .Values.postgres.name | quote }}
            - name: POSTGRES_DB_NAME
              value: {{ .Values.postgres.env.dbName | quote }}
            - name: POSTGRES_DB_USER
              value: {{ .Values.postgres.env.dbUser | quote }}
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_DB_PASSWORD
            - name: KEYCLOAK_DB_NAME
              value: {{ .Values.postgres.env.keycloakDbName | quote }}
            - name: KEYCLOAK_DB_USER
              value: {{ .Values.postgres.env.keycloakDbUser | quote }}
            - name: KEYCLOAK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: KC_DB_PASSWORD
            - name: POSTGRES_CERT_FILE
              value: /opt/postgres/certs/certificate.crt
            - name: POSTGRES_KEY_FILE
              value: /opt/postgres/certs/private.key
            - name: POSTGRES_CA_CERT
              value: {{ .Values.postgres.env.caCertPath | quote }}

          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            exec:
              command: ["sh","-c","pg_isready -h 127.0.0.1 -p {{ .Values.postgres.service.port }} -U {{ .Values.postgres.env.dbUser }} -d {{ .Values.postgres.env.dbName }}"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["sh","-c","pg_isready -h 127.0.0.1 -p {{ .Values.postgres.service.port }} -U {{ .Values.postgres.env.dbUser }} -d {{ .Values.postgres.env.dbName }}"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: {{ .Values.postgres.env.pgdata | quote }}
            {{- if .Values.tls.enabled }}
            - name: qb-tls
              mountPath: /opt/postgres/certs
              readOnly: true
            {{- end }}
  {{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgres.persistence.storageClass }}
        storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size | quote }}
  {{- else }}
  volumeClaimTemplates: []
  {{- end }}
{{- end }}
