{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: redis
    {{- include "qb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
{{- if eq .Values.redis.service.type "NodePort" }}
      nodePort: {{ .Values.redis.service.nodePorts.redis }}
{{- end }}
    - name: redis-tls
      port: {{ .Values.redis.service.tlsPort }}
      targetPort: redis-tls
{{- if eq .Values.redis.service.type "NodePort" }}
      nodePort: {{ .Values.redis.service.nodePorts.rediss }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
    {{- include "qb.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.redis.name }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: redis
        {{- include "qb.labels" . | nindent 8 }}
    spec:
      {{- include "qb.imagePullSecrets" . | nindent 6 }}
      securityContext:
        fsGroup: 10000
      {{- if and .Values.tls.enabled .Values.redis.tls.enabled }}
      volumes:
        - name: qb-tls
          secret:
            secretName: {{ .Values.tls.name }}
            items:
              - key: certificate.crt
                path: certificate.crt
              - key: private.key
                path: private.key
        - name: qb-ca
          secret:
            secretName: {{ .Values.tls.name }}
            items:
              - key: sandbox_ca_root.crt
                path: sandbox_ca_root.crt
      {{- end }}
      containers:
        - name: redis
          image: {{ include "qb.image" (dict "image" .Values.redis.image "global" .Values.global) }}
          imagePullPolicy: {{ include "qb.pullPolicy" (dict "image" .Values.redis.image "global" .Values.global) }}
          command: ["/entrypoint.sh"]
          args: ["redis-server", "/etc/redis/redis.conf"]
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
            - name: redis-tls
              containerPort: {{ .Values.redis.service.tlsPort }}
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: REDIS_PASS
            - name: REDIS_PORT
              value: {{ .Values.redis.service.port | quote }}
            - name: ENABLE_SSL
              value: {{ ternary "true" "" .Values.redis.tls.enabled | quote }}
            - name: TLS_PORT
              value: {{ .Values.redis.service.tlsPort | quote }}
            - name: TLS_CERT_FILE
              value: /opt/redis/certs/certificate.crt
            - name: TLS_KEY_FILE
              value: /opt/redis/certs/private.key
            - name: TLS_CA_CERT_FILE
              value: /etc/pki/ca-trust/source/anchors/sandbox_ca_root.crt
            - name: TLS_CLIENT_CERT_AUTH
              value: {{ ternary "true" "false" .Values.redis.tls.clientCertAuth | quote }}
            - name: REDIS_CONF
              value: /etc/redis/redis.conf

          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            exec:
              command: ["sh","-c","REDISCLI_AUTH=$REDIS_PASS redis-cli -h 127.0.0.1 -p {{ .Values.redis.service.port }} ping | grep -q PONG"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["sh","-c","REDISCLI_AUTH=$REDIS_PASS redis-cli -h 127.0.0.1 -p {{ .Values.redis.service.port }} ping | grep -q PONG"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/redis
            {{- if and .Values.tls.enabled .Values.redis.tls.enabled }}
            - name: qb-tls
              mountPath: /opt/redis/certs
              readOnly: true
            - name: qb-ca
              mountPath: /etc/pki/ca-trust/source/anchors
              readOnly: true
            {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
  {{- else }}
  volumeClaimTemplates: []
  {{- end }}
{{- end }}
